make_outline_task:
  description: >
    Buatlah sebuah outline makalah untuk judul "{judul_makalah}" pada mata kuliah "{mata_kuliah}".
    
    Struktur dan format WAJIB mengikuti aturan ketat berikut:
    Bab 1: Pendahuluan
    - WAJIB berisi HANYA 3 sub-bab: "1.1 Latar Belakang", "1.2 Rumusan Masalah", dan "1.3 Tujuan".
    - TIDAK BOLEH ada tingkatan lebih dalam (seperti 1.1.1).
    Bab 2: Pembahasan
    - Buatlah 3 hingga 5 sub-bab utama yang relevan dengan judul.
    - Format penomoran sub-bab WAJIB dalam bentuk "2.1 Judul", "2.2 Judul", dan seterusnya.
    - DILARANG KERAS membuat sub-bab dengan tingkatan lebih dalam (contohnya: "2.1.1", "2.2.1.a", dll). Cukup satu level saja.
    Bab 3: Penutup
    - WAJIB berisi HANYA 1 sub-bab: "3.1 Kesimpulan".
  expected_output: >
    Sebuah outline makalah yang komprehensif dan penuh detail serta sesuai dengan intruksi
  agent: outline_planner

search_reference_task:
  description: >
    Untuk setiap sub-bab di dalam Bab 2 pada outline yang diberikan, carilah 5-10 referensi per beberapa subab yang relevan dari
    jurnal ilmiah yang relevan. Prioritaskan sumber yang diterbitkan dalam 5-10 tahun terakhir.
  expected_output: >
    Daftar referensi akademis yang relevan untuk setiap sub-bab di Bab 2, lengkap dengan
    judul artikel, penulis, tahun terbit, dan link akses (jika tersedia).
  agent: academic_researcher
  context:
    - make_outline_task